---
- hosts: webservers
  sudo: yes
  vars:
    http_port: 80
    doc_dir: /ansible/
    doc_root: /var/www/html/ansible/
    max_clients: 5
    ansible_python_interpreter: python  

  vars_prompt:
   - name: username
     prompt: What is your name?
   
  tasks:
  - name: Ensure libselinux-python installed
    yum: name=libselinux-python state=present

  - name: Ensure Apache installed
    yum: name=httpd state=present
    when: ansible_os_family == "RedHat"

  - name: Creates directoy
    file: path=/var/www/html/ansible state=directory

  - name: Ensure Apache installed
    yum: name=httpd  state=present
    when: ansible_os_family == "RedHat"

  - name: Ensure Apache is running
    service: name=httpd enabled=yes state=started


  - name: Deploy configuration File
    template: src=templates/httpd.j2 dest=/etc/httpd/conf/httpd.conf
    notify:
      - Restart Apache

 
  - name: Copy Site Files
    template: src=templates/index.j2 dest={{doc_root}}/index.html mode=0644


  
  handlers:
     - name: Restart Apache
       service: name=httpd state=restarted


- hosts: webservers
  sudo: yes

  tasks:
  - name: Stop IPTABLES Now!!
    service: name=iptables state=stopped


